In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
x[2,2] == x[2][2]  # 후자는 비효율적

True

In [7]:
x[1:3, 1:4]   # 슬라이싱은 끝 원소에서 -1

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [8]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
x[np.array([0,3])]   # 넘파이는 배열을 이용해 인덱싱을 할 수 있다.

                     # 인덱스 배열은 반드시 정수형이어야 한다

array([0, 3])

In [17]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
x[np.array([0,3]), np.array([0,3])]   # 다차원 배열에서도 인덱스 배열을 쓸 수 있다
                                      # 인덱스 배열의 값은 좌표값이라고 생각해도 좋다

array([ 0, 15])

In [19]:
x[np.array([0,3]), np.array([0])]     # 브로드캐스팅이 적용된다 np.array([3,0]) 으로.

array([ 0, 12])

# boolean 배열을 인덱스 배열로 쓸 수 있다

In [26]:
x = np.arange(20).reshape(5,4)
y = x % 2 == 0                  # boolean배열 (마스크 인덱스 배열)은 
                                # 초기 차원과 같은 차원이어야 한다
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [27]:
x[y]   # 마스크 인덱스 배열은 True값을 가지는 요소와 같은 위치를 가지는 요소들을 반환하다

       # 마스크 인덱스 배열을 써서 인덱싱을 하면 결과가 1차원 배열로 반환된다

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
x[y] = 0   # y의 True값에 해당하는 x의 원소들을 모두 0으로 만든다.
x

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15],
       [ 0, 17,  0, 19]])